package database.metier;
// Generated 15 sept. 2015 22:10:17 by Hibernate Tools 4.3.1

/**
 * Pays generated by hbm2java
 */
public class Pays implements java.io.Serializable {

	private String nomPays;
	private String nomCapitale;
	private long nbHabitants;

	public Pays() {
	}

	public Pays(String nomPays, String nomCapitale, long nbHabitants) {
		this.nomPays = nomPays;
		this.nomCapitale = nomCapitale;
		this.nbHabitants = nbHabitants;
	}

	public String getNomPays() {
		return this.nomPays;
	}

	public void setNomPays(String nomPays) {
		this.nomPays = nomPays;
	}

	public String getNomCapitale() {
		return this.nomCapitale;
	}

	public void setNomCapitale(String nomCapitale) {
		this.nomCapitale = nomCapitale;
	}

	public long getNbHabitants() {
		return this.nbHabitants;
	}

	public void setNbHabitants(long nbHabitants) {
		this.nbHabitants = nbHabitants;
	}

}
